language: ruby
rvm:
- 2.2.5
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
branches:
  only:
  - master
install:
- bundle install
script:
- bundle exec jekyll build
- timeout 5m bundle exec htmlproofer ./_site --check-html --check-favicon --allow-hash-href
  --external_only --only-4xx --http-status-ignore 429
after_success: s3_website push
notifications:
  slack:
    rooms:
      - secure: InMBgp2bT6Spwvfm4D7iUdF5YQYdTewgICcqvYI8LfN9VRwc9tzOLR+NJOuUUFcfIT/eCvScNNaAAxXwD7W1FsYyosQW1E541yWLRQOo2O4EMnP6oKwA/IWK5ntyrsBPHKvj/ru3NIab8+myA82ZmnC+GC6J+OInogWqwGXyD7X1a2Aj1ayEZ6ft8udFKSRM1AZ7puzT6lm0vIn6fGjcuEEwCI0KIkqo///D5u/Si1zofUY9DIYR4bi+LG4NhTDGllsMtFHS3NRGjii+kgpsRurwmOBb0MY5goK8jWi8kI5xlSQZV4rvOafPj42z+4JKv6llT8NEsnshhXeoiKhh0oixkVT3ehAAej0PHvVTXGs/hiGy3fcgdjzyC8UJy288SCUopmy1Djj/MoQD7ARrSFXebAWqwdiceboeJH6FtgohU5Fepf+QQrn/j0xXElFclRmK6vcZHTT2xFEga+t9mMexGQVTLW5EEgkl7t/wYNr0xbDFHPc5n9ZUsdTJBhYTbbVguDKhKxpEKDIIcLoWTwnR4Tq2wbAog5cHyDNA2UpIxUnvVz30QFubB1sICihgzhgFI/uo1dzbgFverh+l/kXrI3vpO1YutHJ0CpmULH/PwNk5zfwmnkFdBzQnTGAlfDDuJv/4XmsvGjXKhJByxakc+tL0sDlnvEh8ETwuHRY=
    on_success: always
