---
# Program/Department Title
title: Geography and Urban Studies
# Subdirectory (with / at only at beginning)
baseurl: /geography-and-urban-studies
# Production domain (without / at the end)
production: https://www.cla.temple.edu
# url spits sitemap
url: https://www.cla.temple.edu/geography-and-urban-studies

# Development Config
# If you do not have access to 'tutheme', use 'minima' instead.
theme: tutheme
palette: light #future feature

# Program Information
# Short tagline for tweets (<100 characters)
tagline: This is our life's work
# Longer descriptions for link previews (<250 characters)
description: 'Geography is the study of the interaction of people, places and the environment. Urban Studies is the examination of metropolitan life, processes and problems. Our students are equipped to understand and address a wide range of environmental, economic, social and political challenges that are central to the well-being of billions of people in an urbanizing world.'
# List of related keywords for search engines
keywords: highered, college, university, philadelphia, Temple

# Address
address:
  building: Gladfelter Hall
  room: 308
  street: 1115 Polett Walk
  city: Philadelphia, PA 19122
  email: geography-urban-studies@temple.edu
  phone: 215-204-7692 #if there is a number it will be in the footer. Fear these numbers don't work.
  
  
  # University & College Information
university:
  name: Temple University
  url: https://temple.edu/
college:
  name: College of Liberal Arts
  url: https://liberalarts.temple.edu/
  
program_news: https://liberalarts.temple.edu/news/geography-and-urban-studies
program_events: https://events.temple.edu/department/geography-and-urban-studies
  
 
# CSV/JSON/YAML data feeds URLs, to be fetched before each build
events-feed: https://liberalarts.temple.edu/events/geography-and-urban-studies/csv
news-feed: https://liberalarts.temple.edu/articles/geography-and-urban-studies/csv
articles-feed: https://liberalarts.temple.edu/articles/geography-and-urban-studies/csv
faculty-feed: https://liberalarts.temple.edu/profiles/geography-and-urban-studies/csv
media-mentions-feed: https://liberalarts.temple.edu/media-mentions/geography-and-urban-studies/csv
  

# Social Media
# Put in only the username unless otherwise noted
# If social media does not apply to your department, keep it blank or use the default values.
social:
  # Facebook - https://www.facebook.com/USERNAME
  # if your page does not have a custom URL, create one!
  facebook: TempleGUS
  # Twitter - https://twitter.com/USERNAME
  twitter: TempleGUS
  # Instagram - https://instagram.com/USERNAME
  instagram: TempleGUS
  # Snapchat - USERNAME
  snapchat:
  # GitHub - https://github.com/USERNAME or https://github.com/USERNAME/REPO
  github:
  # DeviantArt - http://USERNAME.deviantart.com/
  deviantart:
  # Vimeo - https://vimeo.com/USERNAME
  vimeo:
  # YouTube - Paste the FULL URL below
  youtube:
  # LinkedIn - Paste the FULL URL below
  linkedin:
  # Slack - Paste the FULL URL below
  slack:
  # Google Tag Manager OR Google Analytics
  google_analytics:
  google_tag_manager: GTM-58ZL5B


# Global Site Config
# DO NOT edit below unless if you know what you're doing!
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
timezone: UTC
collections:
  pages:
    title: Pages
    output: true
    layout: page
permalink: /:title

# Prose
prose:
  rooturl: pages
  media: media
  ignore:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - README.md
  - index.html
  - _config.yml
  metadata:
    pages:
      - name: title
        field:
          element: text
          label: Title
      - name: permalink
        field:
          element: text
          label: Permalink
      - name: layout
        field:
          element: select
          label: Page layout
          options:
            - name: page
              value: page
            - name: faculty
              value: faculty
            - name: faculty2
              value: faculty2
            - name: home
              value: home

# Jekyll Ignore
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.md
  - s3_website.yml
  - .sass-cache
  - .travis.yml
  - .ruby-version
  - .gitignore
  - vendor
  - _site
  - node_modules
